package core.Tasks;

public enum TaskType {
    CLEAN,
    STOCK,
    INVENTORY,
    PRICETAGS,
    SECURITY,
    PHARMACY,
    FLORAL,
    MEAT,
    ONLINE_ORDER,
    VENDOR,
    RECEIPT_VERIFICATION,
    BAKERY,
    PRODUCE,
    RESTAURANT,
    WINEANDSPIRITS,
    FROZENANDDAIRY,
    FULFILLMENT,
}